name: ebisu
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
description: >
  A library that supports code generation of the structure Dart (and potentially
  other languages like D) using a fairly declarative aproach.
  
dependencies:
  path:  "any"
  logging:  "any"
  logging_handlers:  "any"
# custom <ebisu dependencies>

  id:
    git:
      url: git://github.com/patefacio/id
      ref: HEAD

  logging:
  logging_handlers:

# end <ebisu dependencies>

