name: my_pub_package
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
# custom <my_pub_package dependencies>
# end <my_pub_package dependencies>

dev_dependencies:
# custom <my_pub_package dev dependencies>
# end <my_pub_package dev dependencies>


